server:
  host: "http://localhost"
  port: 3500
  use_cors: true

drive_auth:
  credentials_file_path: "./credentials.json" # Path relative to execution directory
  path_to_save_token: "./token.json" # Path relative to execution directory